In [1]:
import numpy as np
from bbh.sim import GadgetSnapshot, ParticleType

In [2]:
ic = GadgetSnapshot()

In [3]:
print(ic.header)

GADGET HEADER
Npart:             array([0, 0, 0, 0, 0, 0])
Massarr:           array([0., 0., 0., 0., 0., 0.])
Time:              0
Redshift:          0
FlagSfr:           0
FlagFeedback:      0
Nall:              array([0, 0, 0, 0, 0, 0])
FlagCooling:       0
NumFiles:          0
BoxSize:           0
Omega0:            0.0
OmegaLambda:       0.0
HubbleParam:       1.0
FlagAge:           0
FlagMetals:        0
NallHW:            0
flag_entr_ics:     0



In [4]:
ic.header.Massarr[ParticleType.Gas]

0.0

In [5]:
ic.pos

array([], shape=(0, 3), dtype=float64)

In [6]:
id_1 = ic.add(1, np.zeros(3), np.zeros(3), mass=1)

In [7]:
id_2 = ic.add(1, np.zeros(3) + 1, np.zeros(3), mass=2)

In [8]:
ic.pos

array([[0., 0., 0.],
       [1., 1., 1.]])

In [9]:
index_1 = ic.indexof(id_1)
index_2 = ic.indexof(id_2)

In [10]:
ic.pos[index_1]

array([0., 0., 0.])

In [11]:
ic.pos[index_2]

array([1., 1., 1.])

In [12]:
ic.masses

array([1., 2.])

In [13]:
print(ic.header)

GADGET HEADER
Npart:             array([0, 2, 0, 0, 0, 0])
Massarr:           array([0., 0., 0., 0., 0., 0.])
Time:              0
Redshift:          0
FlagSfr:           0
FlagFeedback:      0
Nall:              array([0, 2, 0, 0, 0, 0])
FlagCooling:       0
NumFiles:          0
BoxSize:           0
Omega0:            0.0
OmegaLambda:       0.0
HubbleParam:       1.0
FlagAge:           0
FlagMetals:        0
NallHW:            0
flag_entr_ics:     0



In [14]:
ic.header.Massarr[ParticleType.Gas] = 1.

In [15]:
for _ in range(1000):
    ptype = ParticleType(np.random.choice(ParticleType))
    if ptype == ParticleType.Gas:
        mass = None
    else:
        mass = np.random.uniform()
    position = np.random.uniform(size=3)
    velocity = np.random.uniform(size=3)
    ic.add(ptype, position, velocity, mass)

In [16]:
print(ic.header)

GADGET HEADER
Npart:             array([166, 164, 165, 170, 183, 154])
Massarr:           array([1., 0., 0., 0., 0., 0.])
Time:              0
Redshift:          0
FlagSfr:           0
FlagFeedback:      0
Nall:              array([166, 164, 165, 170, 183, 154])
FlagCooling:       0
NumFiles:          0
BoxSize:           0
Omega0:            0.0
OmegaLambda:       0.0
HubbleParam:       1.0
FlagAge:           0
FlagMetals:        0
NallHW:            0
flag_entr_ics:     0



In [17]:
len(ic.masses)

836

This should include all particles except gas particles, which get their mass from `Massarr`. Let's count how many of these there are.

In [18]:
np.sum(ic.header.Npart[1:])

836