In [85]:
# Testing the reading of some initial conditions for Gadget-2 N-body Simulator.
import numpy



with open("lcdm_gas_littleendian.dat", "rb") as binary_data:
    chunk_size = 16
    data = binary_data.read(chunk_size)
    print(data)
    
import sys
from functools import partial

# chunk_size = 1
# with open("lcdm_gas_littleendian.dat", "rb") as in_file:    
#     for data in iter(partial(in_file.read, chunk_size), b''):
#         x = int.from_bytes(data, byteorder='big')
#         if (x > 64 and x < 91) or (x > 96 and x < 123) :
#             sys.stdout.write(chr(x))
#         else:
#             sys.stdout.write('.')

from struct import *


buffer = calcsize(data)
unpack('I', b'\x00\x01\x00\x00')


print('\n\n\n')


with open("lcdm_gas_littleendian.dat", "rb") as f:
    for k in range(4):
        data = numpy.fromfile(f, dtype=np.float32, count = 2*3)
        print (numpy.reshape(data,(2,3)))
        
        
print('\n\n\n')


f = open("lcdm_gas_littleendian.dat", "rb")
recl = numpy.fromfile(f, dtype='int32', count=1)
f.seek(4)
field = numpy.fromfile(f, dtype='float32')

print('Record length=',recl)
print(field)


print('\n\n\n')


f = open("lcdm_gas_littleendian.dat", "rb")
field = np.fromfile(f, dtype='float32')

print(field)


print('\n\n\n')


# from scipy.io import FortranFile
# f = FortranFile("lcdm_gas_littleendian.dat", "r")
# print(f.read_ints(numpy.int32))
# print(f.read_reals(float).reshape((5,4), order="F"))
# f.close()
# >>> Doesn't properly function!




b'\x00\x01\x00\x00\x00\x80\x00\x00\x00\x80\x00\x00\x00\x00\x00\x00'




[[3.5873e-43 4.5918e-41 4.5918e-41]
 [0.0000e+00 0.0000e+00 0.0000e+00]]
[[ 0.0000000e+00 -7.4189471e+17  2.2646921e+00]
 [-5.6241227e+04  2.9301248e+00  0.0000000e+00]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0.0000000e+00 7.0066507e+31 1.4318181e+00]
 [0.0000000e+00 2.5625000e+00 0.0000000e+00]]




Record length= [256]
[4.59177e-41 4.59177e-41 0.00000e+00 ... 0.00000e+00 0.00000e+00
 1.83671e-40]




[3.58732e-43 4.59177e-41 4.59177e-41 ... 0.00000e+00 0.00000e+00
 1.83671e-40]






# Header:
## struct io_header;

In [86]:
# HEADER FIELD BYTE FORMATTING:

# >>>(Npart[6])
# calcsize('6I')
# # 24 bytes for six unsigned ints (Npart[6])

# >>>(Massarr[6])
# calcsize('6d')
# # 48 bytes for six doubles (Massarr[6])

# >>>(Time)
# calcsize('1d')
# # 8 bytes for a single double (Time)

# >>>(Redshift)
# calcsize('1d')
# # 8 bytes for a single double (Redshift)

# >>>(FlagSfr)
# calcsize('1i')
# # 4 bytes for an int (FlagSfr)

# >>>(FlagFeedback)
# calcsize('1i')
# # 4 bytes for an int (FlagFeedback)

# >>>(Nall[6])
# calcsize('6i')
# # 24 bytes for six ints (Nall[6])

# >>>(FlagCooling)
# calcsize('1i')
# # 4 bytes for an int (FlagCooling)

# >>>(NumFiles)
# calcsize('1i')
# # 4 bytes for an int (NumFiles)

# >>>(BoxSize)
# calcsize('1d')
# # 8 bytes for a double (BoxSize)

# >>>(Omega0)
# calcsize('1d')
# # 8 bytes for a double (Omega0)

# >>>(OmegaLambda)
# calcsize('1d')
# # 8 bytes for a double (OmegaLambda)

# >>>(HubbleParam)
# calcsize('1d')
# # 8 bytes for a double (HubbleParam)

# >>>(FlagAge)
# calcsize('1i')
# # 4 bytes for an int (FlagAge)

# >>>(FlagMetals)
# calcsize('1i')
# # 4 bytes for an int (FlagMetals)

# >>>(NallHW[6])
# calcsize('6i')
# # 24 bytes for six ints (NallHW[6])

# >>>(flag_entr_ics)
# calcsize('1i')
# # 4 bytes for an int (flag_entr_ics)

# >>>(unused)
# calcsize('1i')
# # 4 bytes for an int (unused)




SyntaxError: invalid syntax (<ipython-input-86-0c7b18f2fbe9>, line 1)

In [139]:

with open("lcdm_gas_littleendian.dat", "rb") as binary_data:
    chunk_size = calcsize('1I')
    block_length = binary_data.read(chunk_size)
    print(block_length)
    block_length_convert = unpack('1I', block_length)
    print('Entire Block Length:', block_length_convert, '\n')
    
    chunk_size = calcsize('6I')
    # 24 bytes for six unsigned ints (Npart[6])
    Npart = binary_data.read(chunk_size)
    print(Npart)
    Npart_convert = unpack('6I', Npart)
    print('Npart[6]:', Npart_convert, '\n')
    
    chunk_size = calcsize('6d')
    # 48 bytes for six doubles (Massarr[6])
    Massarr = binary_data.read(chunk_size)
    print(Massarr)
    Massarr_convert = unpack('6d', Massarr)
    print('Massarr[6]:', Massarr_convert, '\n')
    
    chunk_size = calcsize('1d')
    # 8 bytes for a single double (Time)
    Time = binary_data.read(chunk_size)
    print(Time)
    Time_convert = unpack('1d', Time)
    print('Time:', Time_convert, '\n')
    
    chunk_size = calcsize('1d')
    # 8 bytes for a single double (Redshift)
    Redshift = binary_data.read(chunk_size)
    print(Redshift)
    Redshift_convert = unpack('1d', Redshift)
    print('Redshift:', Redshift_convert, '\n')
    
    chunk_size = calcsize('1i')
    # 4 bytes for an int (FlagSfr)
    FlagSfr = binary_data.read(chunk_size)
    print(FlagSfr)
    FlagSfr_convert = unpack('1i', FlagSfr)
    print('FlagSfr:', FlagSfr_convert, '\n')
    
    chunk_size = calcsize('1i')
    # 4 bytes for an int (FlagFeedback)
    FlagFeedback = binary_data.read(chunk_size)
    print(FlagFeedback)
    FlagFeedback_convert = unpack('1i', FlagFeedback)
    print('FlagFeedback:', FlagFeedback_convert, '\n')
    
    chunk_size = calcsize('6i')
    # 24 bytes for six ints (Nall[6])
    Nall = binary_data.read(chunk_size)
    print(Nall)
    Nall_convert = unpack('6i', Nall)
    print('Nall[6]:', Nall_convert, '\n')
    
    chunk_size = calcsize('1i')
    # 4 bytes for an int (FlagCooling)
    FlagCooling = binary_data.read(chunk_size)
    print(FlagCooling)
    FlagCooling_convert = unpack('1i', FlagCooling)
    print('FlagCooling:', FlagCooling_convert, '\n')
    
    chunk_size = calcsize('1i')
    # 4 bytes for an int (NumFiles)
    NumFiles = binary_data.read(chunk_size)
    print(NumFiles)
    NumFiles_convert = unpack('1i', NumFiles)
    print('NumFiles:', NumFiles_convert, '\n')
    
    chunk_size = calcsize('1d')
    # 8 bytes for a double (BoxSize)
    BoxSize = binary_data.read(chunk_size)
    print(BoxSize)
    BoxSize_convert = unpack('1d', BoxSize)
    print('BoxSize:', BoxSize_convert, '\n')

    chunk_size = calcsize('1d')
    # 8 bytes for a double (Omega0)
    Omega0 = binary_data.read(chunk_size)
    print(Omega0)
    Omega0_convert = unpack('1d', Omega0)
    print('Omega0:', Omega0_convert, '\n')

    chunk_size = calcsize('1d')
    # 8 bytes for a double (OmegaLambda)
    OmegaLambda = binary_data.read(chunk_size)
    print(OmegaLambda)
    OmegaLambda_convert = unpack('1d', OmegaLambda)
    print('OmegaLambda:', OmegaLambda_convert, '\n')
    
    chunk_size = calcsize('1d')
    # 8 bytes for a double (HubbleParam)
    HubbleParam = binary_data.read(chunk_size)
    print(HubbleParam)
    HubbleParam_convert = unpack('1d', HubbleParam)
    print('HubbleParam:', HubbleParam_convert, '\n')

    chunk_size = calcsize('1i')
    # 4 bytes for an int (FlagAge)
    FlagAge = binary_data.read(chunk_size)
    print(FlagAge)
    FlagAge_convert = unpack('1i', FlagAge)
    print('FlagAge:', FlagAge_convert, '\n')
    
    chunk_size = calcsize('1i')
    # 4 bytes for an int (FlagMetals)
    FlagMetals = binary_data.read(chunk_size)
    print(FlagAge)
    FlagMetals_convert = unpack('1i', FlagMetals)
    print('FlagMetals:', FlagMetals_convert, '\n')
    
    chunk_size = calcsize('6i')
    # 24 bytes for six ints (NallHW[6])
    NallHW = binary_data.read(chunk_size)
    print(NallHW)
    NallHW_convert = unpack('6i', NallHW)
    print('NallHW[6]:', NallHW_convert, '\n')
    
    chunk_size = calcsize('1i')
    # 4 bytes for an int (flag_entr_ics)
    flag_entr_ics = binary_data.read(chunk_size)
    print(flag_entr_ics)
    flag_entr_ics_convert = unpack('1i', flag_entr_ics)
    print('flag_entr_ics:', flag_entr_ics_convert, '\n')
    
    # UNUSED SPACE:
    
    chunk_size = calcsize('')
    # 4 bytes for an int (unused)
    unused = binary_data.read(chunk_size)
    print(unused)
    unused_convert = unpack('', unused)
    print('unused:', unused_convert, '\n')
    
    
    


b'\x00\x01\x00\x00'
Entire Block Length: (256,) 

b'\x00\x80\x00\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Npart[6]: (32768, 32768, 0, 0, 0, 0) 

b'\xd5\xbb$\xdd\xb7\xf0\x10@:\xb1[\xc7*\x87;@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Massarr[6]: (4.235076384894417, 27.52799650181371, 0.0, 0.0, 0.0, 0.0) 

b'F\x17]t\xd1E\xb7?'
Time: (0.09090909090909091,) 

b'\x00\x00\x00\x00\x00\x00$@'
Redshift: (10.0,) 

b'\x00\x00\x00\x00'
FlagSfr: (0,) 

b'\x00\x00\x00\x00'
FlagFeedback: (0,) 

b'\x00\x80\x00\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Nall[6]: (32768, 32768, 0, 0, 0, 0) 

b'2y\x06\x00'
FlagCooling: (424242,) 

b'\x00\x00\x00\x00'
NumFiles: (0,) 

b'\x00\x00\x00\x00\x00\x00\x00\x00'
BoxSize: (0.0,) 

b'\x00\x00\x00\x00\x00\x00\x00\x00'
Omega0: (0.0,) 

b'\x00\x00\x00\x00\x00\x00\x00\x00'
OmegaLambda: (0.0,) 

b'\x0

# Block ID
## 2-12 excluding HEAD

In [159]:

with open("lcdm_gas_littleendian.dat", "rb") as binary_data:
    chunk_size = 256 # length of header block
    header = binary_data.read(chunk_size)
    print(header)
    
    
    # particle_positions
    
    chunk_size = calcsize('1f')
    particle_positions = binary_data.read(chunk_size)
    print(particle_positions)
    particle_positions_convert = unpack('1f', particle_positions)
    print('particle positions:', particle_positions_convert, '\n')
    
    
    # particle_velocities
    
    chunk_size = calcsize('1f')
    particle_velocities = binary_data.read(chunk_size)
    print(particle_velocities)
    particle_velocities_convert = unpack('1f', particle_velocities)
    print('particle velocities:', particle_velocities_convert, '\n')
    
    
    # particle_identifications
    
    chunk_size = calcsize('1I')
    particle_identifications = binary_data.read(chunk_size)
    print(particle_identifications)
    particle_identifications_convert = unpack('1I', particle_identifications)
    print('particle identifications:', particle_identifications_convert, '\n')
    
    
    # variable_particle_masses
    
    chunk_size = calcsize('1f')
    variable_particle_masses = binary_data.read(chunk_size)
    print(variable_particle_masses)
    variable_particle_masses_convert = unpack('1f', variable_particle_masses)
    print('variable_particle_masses:', variable_particle_masses_convert, '\n')
    
    
    # internal_energy
    
    chunk_size = calcsize('1f')
    internal_energy = binary_data.read(chunk_size)
    print(internal_energy)
    internal_energy_convert = unpack('1f', internal_energy)
    print('internal_energy:', internal_energy_convert, '\n')
    
    
    # density
    
    chunk_size = calcsize('1f')
    density = binary_data.read(chunk_size)
    print(density)
    density_convert = unpack('1f', density)
    print('density:', density_convert, '\n')
    
    
    # smoothing_length
    
    chunk_size = calcsize('1f')
    smoothing_length = binary_data.read(chunk_size)
    print(smoothing_length)
    smoothing_length_convert = unpack('1f', smoothing_length)
    print('smoothing_length:', smoothing_length_convert, '\n')
    
    
    # gravitational_potential
    
    chunk_size = calcsize('1f')
    gravitational_potential = binary_data.read(chunk_size)
    print(gravitational_potential)
    gravitational_potential_convert = unpack('1f', gravitational_potential)
    print('gravitational_potential:', gravitational_potential_convert, '\n')
    
    
    # accelerations
    
    chunk_size = calcsize('1f')
    accelerations = binary_data.read(chunk_size)
    print(accelerations)
    accelerations_convert = unpack('1f', accelerations)
    print('accelerations:', accelerations_convert, '\n')
    
    
    # rate_of_entropy_production
    
    chunk_size = calcsize('1f')
    rate_of_entropy_production = binary_data.read(chunk_size)
    print(rate_of_entropy_production)
    rate_of_entropy_production_convert = unpack('1f', rate_of_entropy_production)
    print('rate_of_entropy_production:', rate_of_entropy_production_convert, '\n')
    
    
    #  timesteps_of_particles
    
    chunk_size = calcsize('1f')
    timesteps_of_particles = binary_data.read(chunk_size)
    print(timesteps_of_particles)
    timesteps_of_particles_convert = unpack('1f', timesteps_of_particles)
    print('timesteps_of_particles:', timesteps_of_particles_convert, '\n')
    
    chunk_size = 10
    test = binary_data.read(chunk_size)
    print(test)
    
    
    

b'\x00\x01\x00\x00\x00\x80\x00\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xd5\xbb$\xdd\xb7\xf0\x10@:\xb1[\xc7*\x87;@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00F\x17]t\xd1E\xb7?\x00\x00\x00\x00\x00\x00$@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x00\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x002y\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
